drop view mb_views.top_stores;
drop view mb_views.nft_tokens_with_listing;
drop view mb_views.nft_metadata_unburned;
drop view mb_views.nft_activities;
drop view mb_views.active_listings_rollup;
drop view mb_views.active_listings;
drop view mb_views.nft_tokens;
drop view mb_views.nft_metadata;
drop schema mb_views;
