name: CommonHasuraCICD

on:
  push:
    branches:
      - main

jobs:
  # this is a full redeploy! in perspective, this should do DB migratons, and
  # then just start from the current block height
  deploy:
    runs-on: ubuntu-22.04
    name: Diesel and Hasura migrations
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Diesel setup
        run: |
          sudo apt-get install libpq-dev && cargo install diesel_cli

      - name: Hasura setup
        run: |
          sudo apt-get install curl
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Redeployment script
        # TODO: once stable, run testnet redeployment as well
        run: |
          echo "${{ secrets.SANDBOX_ENV }}" > sandbox.env
          scripts/redeploy.sh sandbox latest
