name: Minterop CICD

on:
  push:
    branches:
      - main

jobs:
  workspace:
    runs-on: ubuntu-22.04
    name: Build minterop commons workspace
    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Set up docker auth"
        run: gcloud auth configure-docker

      # Build and push docker image
      - name: "Build Workspace Image & Push"
        run: |
          docker build \
            -t gcr.io/omni-cloud-1/minterop-workspace:${GITHUB_SHA::6} \
            -t gcr.io/omni-cloud-1/minterop-workspace:latest \
            .
          docker push gcr.io/omni-cloud-1/minterop-workspace:${GITHUB_SHA::6}
          docker push gcr.io/omni-cloud-1/minterop-workspace:latest

  # this is a full redeploy! in perspective, this should do DB migratons, and
  # then just start from the current block height
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy and run indexer
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Diesel setup
        run: |
          sudo apt-get install libpq-dev && cargo install diesel_cli

      - name: Hasura setup
        run: |
          sudo apt-get install curl
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      # get secrets from GH
      # TODO: currently a problem for CD: this defines the block height
      # -> only good for redeploy + sandbox
      - name: Redeployment script
        # TODO: use commit hash again
        run: |
          echo "${{ secrets.SANDBOX_ENV }}" > sandbox.env
          scripts/redeploy.sh sandbox latest
        # run: |
        #   echo "${{ secrets.SANDBOX_ENV }}" > sandbox.env
        #   scripts/redeploy.sh sandbox ${GITHUB_SHA::6}
