name: Testnet and mainnet Deployment

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Diesel and Hasura migrations
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Diesel setup
        run: |
          sudo apt-get install libpq-dev && cargo install diesel_cli

      - name: Hasura setup
        run: |
          sudo apt-get install curl
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: jq setup
        uses: dcarbone/install-jq-action@v1.0.0
        with:
          version: 1.6

      - name: Redeployment script (testnet)
        run: |
          echo "${{ secrets.TESTNET_ENV }}" > testnet.env
          scripts/redeploy.sh testnet

      - name: Redeployment script (mainnet)
        run: |
          echo "${{ secrets.MAINNET_ENV }}" > mainnet.env
          scripts/redeploy.sh mainnet
